package org.littleshoot.proxy.ntlm;

/**
 * Implementation may use some library like jCIFS to deal with various NTLM
 * messages.
 *
 * <a href="http://davenport.sourceforge.net/ntlm.html">Reference</a>
 */
public interface NtlmProvider {

	/**
	 * This primarily contains a list of features supported by the client and
	 * requested of the server.
	 *
	 * @return Type 1 (negotiation)
	 */
	byte[] getType1();

	/**
	 * This contains a list of features supported and agreed upon by the server.
	 * Most importantly, however, it contains a challenge generated by the
	 * server.
	 *
	 * @param material
	 *            Type 2 (challenge)
	 * @return Whether the client was able to parse the challenge
	 */
	boolean setType2(byte[] material);

	/**
	 * This contains several pieces of information about the client, including
	 * the domain and username of the client user. It also contains one or more
	 * responses to the Type 2 challenge.
	 *
	 * @return Type 3 (authentication)
	 */
	byte[] getType3();

}
